name: build on new obsidian version

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
   - workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
#testing auto versioning         
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: major
#########

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get latest Obsidian version
        id: obver
        run: |
          echo "::set-output name=OBVERSION::$(curl -s https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest | perl -nle'print $& while m#"name": "\K[^"]*#g' | head -1)"
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: ./Dockerfile
          build-args: OBSIDIAN_VERSION=${{ steps.obver.outputs.OBVERSION }}
          push: true
          tags: ${{ steps.tag_version.outputs.new_tag }}
#testing auto versioning + auto release
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
#########
